- name: Update and upgrade Homebrew
  homebrew: update_homebrew=yes upgrade_all=yes
  tags:
    - brew
    - upgrade

- name: Homebrew install packages
  homebrew: name={{ item }} state=latest
  with_items:
    - curl
    - git
    - wget
    - python
    - python3
    - vim
    - bash-completion
  tags:
    - brew